# SPDX-FileCopyrightText: Copyright © contributors to CNPG Extensions.
# SPDX-License-Identifier: Apache-2.0

{{ $packageName := replaceAll .Package "%version%" "${PG_MAJOR}" }}
ARG BASE=ghcr.io/cloudnative-pg/postgresql:{{ .DefaultVersion }}-minimal-{{ .DefaultDistro }}
FROM $BASE AS builder

ARG PG_MAJOR
ARG EXT_VERSION

USER 0

# TODO: Remove this comment block after customizing the Dockerfile
# Instructions:
# 1. Remove all TODO comment blocks after completing the customization.
# 2. Uncomment and customize the COPY/RUN commands below.
# 3. If your extension requires additional system libraries, ensure they are
#    copied to /lib.

# Install extension via `apt-get`
# RUN apt-get update && apt-get install -y --no-install-recommends \
#       "{{ $packageName }}=${EXT_VERSION}"

FROM scratch
ARG PG_MAJOR

# Licenses
# TODO: Uncomment and customize the COPY command below
# Including license files is essential for legal compliance and transparency.
# It ensures proper attribution to original authors, fulfills open source license
# requirements, and enables automated compliance scanning tools to verify licensing.
# COPY --from=builder /usr/share/doc/{{ $packageName }}/copyright /licenses/{{ $packageName }}/

# Libraries
# TODO: Uncomment and customize the COPY command below
# Include the extension's shared objects and related dependencies under the /lib directory.
# CNPG will configure PostgreSQL to locate these libraries at runtime by configuring
# the "dynamic_library_path" GUC to include this path.
# For more details, see: https://cloudnative-pg.io/docs/current/imagevolume_extensions#how-it-works
# COPY --from=builder /usr/lib/postgresql/${PG_MAJOR}/lib/{{ .Name }}* /lib/

# Share
# TODO: Uncomment and customize the COPY command below
# Include the extension's SQL scripts and control files under the /share/extension directory.
# CNPG will configure PostgreSQL to include this path via the "extension_control_path" GUC to
# seamlessly find and manage the current extension.
# For more details, see: https://cloudnative-pg.io/docs/current/imagevolume_extensions#how-it-works
# COPY --from=builder /usr/share/postgresql/${PG_MAJOR}/extension/{{ .Name }}* /share/extension/

USER 65532:65532
